package io.spicelabs.rodeocomponents.APIS.artifacts;

/* Copyright 2026 Stephen Hawley, Spice Labs, Inc. & Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

import io.spicelabs.rodeocomponents.APIS.purls.Purl;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.List;
import java.util.Optional;

/**
 * Defines the interface for a component based artifact handler. An implementation of this class will
 * be called through these methods to collect data about the artifact. 
 */
public interface ArtifactHandler {
  /**
   * Called to determine if the artifact requires a FileInputStream to do processing
   * @return true if the handler requires a FileInputStream, false otherwise
   */
  boolean requiresFile();
  /**
   * Called at the start of processing of an artifact. This method will only be called if {@link #requiresFile()} returns false.
   * @param stream The stream representing the artifact
   * @param artifact The artifact to be processed
   * @param item An item that accumulates information about the artifact
   * @param marker A component defined marker for the artifact
   * @return A component defined memento that will be supplied to the component in subsequent calls.
   */
  ArtifactMemento begin(InputStream stream, RodeoArtifact artifact, WorkItem item, RodeoItemMarker marker);
  /**
   * Called at the start of processing of an artifact. This method will only be called if {@link  #requiresFile() true. }
   * @param stream The stream representing the artifact
   * @param artifact The artifact to be processed
   * @param item An item that accumulates information about the artifact
   * @param marker A component defined marker for the artifact
   * @return A component defined memento that will be supplied to the component in subsequent calls.
   */
  ArtifactMemento begin(FileInputStream stream, RodeoArtifact artifact, WorkItem item, RodeoItemMarker marker);
  /**
   * Get package URLS that are associated with this artifact.
   * @param memento The memento that was returned by the previous call to begin
   * @param artifact The artifact to be processed
   * @param item An item that accumulates information about the artifact
   * @param marker A component defined marker for the artifact
   * @return A list of {@link Purl} objects to associate with the artifact
   */
  List<Purl> getPurls(ArtifactMemento memento, RodeoArtifact artifact, WorkItem item, RodeoItemMarker marker);
  /**
   * Get metadata to be associated with this artifact
   * @param memento The memento that was returned by the previous call to begin
   * @param artifact The artifact to be processed
   * @param item An item that accumulates information about the artifact
   * @param marker A component defined marted for the artifact
   * @return A list of {@link Metadata} objects to associate with the artifact
   */
  List<Metadata> getMetadata(ArtifactMemento memento, RodeoArtifact artifact, WorkItem item, RodeoItemMarker marker);
  /**
   * Provide an opportunity to add to the existing information about an artifact.
   * @param memento The memento that was returned by the previous call to begin
   * @param artifact The artifact to be processed
   * @param item An item that accumulates information about the artifact
   * @param parent The parent of the artifact
   * @param storage Storage for processed data
   * @param marker A component defined marted for the artifact
   * @return A possibly augmented WorkItem for the artifact.
   */
  WorkItem augment(ArtifactMemento memento, RodeoArtifact artifact, WorkItem item, ParentFrame parent, BackendStorage storage, RodeoItemMarker marker);
  /**
   * Provide an opportunity to do any processing after any children of this node have been processed.
   * @param memento The memento that was returned by the previous call to begin
   * @param gitoids Gitoids that have been generated by processing this artifact
   * @param storage Storage for processed data
   * @param marker A component defined marted for the artifact
   */
  void postChildProcessing(ArtifactMemento memento, Optional<List<String>> gitoids, BackendStorage storage, RodeoItemMarker marker);
  /**
   * Called at the end of processing of an artifact.
   * @param memento The memento that was returned by the previous call to begin
   */
  void end(ArtifactMemento memento);
}
